### DATA ACQUISITION

In [12]:
import pandas as pd
from pathlib import Path
from functions import utils
import os

Path("data/cleaned_data").mkdir(parents=True, exist_ok=True)
Path("data/semi_cleaned_data").mkdir(parents=True, exist_ok=True)
Path("data/uncleaned_data/doe_pdf").mkdir(parents=True, exist_ok=True)

## Section 1: Data Acquisition

### 1.1 Brent/WTI Prices Acquisition from EIA

In [2]:
utils.download_eia_dataset(output_folder='data/semi_cleaned_data')

Fetching Brent_Price_USD prices from 2020-01-01...
Fetching WTI_Price_USD prices from 2020-01-01...
Merging Brent and WTI datasets...
Success! Saved EIA data to data/semi_cleaned_data\Brent_WTI_Prices_2020_to_Present.csv

### 1.2 Weekly Retail Pump Prices from DOE

In [3]:
utils.download_doe_pdfs(output_folder='data/uncleaned_data/doe_pdf')

Authenticating with DOE portal...
Found 270 protected PDF(s). Downloading...
Saved: petro_ncr_2021-dec-16_0-pdf.pdf
Saved: ncr-price-monitoring-08122025-pdf.pdf
Saved: petro_ncr_2021-feb-18.pdf
Saved: petro_ncr_2021-jul-15-pdf.pdf
Saved: petro_ncr_2022-apr-07.pdf
Saved: ncr-price-monitoring-04222025-pdf.pdf
Saved: petro_ncr_2025_feb-25-mar-3-pdf.pdf
Saved: petro_ncr_2024-apr-2-8.pdf
Saved: petro_ncr_2024-mar-19.pdf
Saved: petro_ncr_2023-sep-28-pdf.pdf
Saved: petro_ncr_2022-apr-15.pdf
Saved: ncr-price-monitoring-05202025-pdf.pdf
Saved: petro_ncr_2025_mar-4-10-pdf.pdf
Saved: ncr-price-monitoring-08052025-pdf.pdf
Saved: ncr-price-monitoring-12162025-pdf.pdf
Saved: ncr-price-monitoring-09162025-pdf.pdf
Saved: petro_ncr_2024-may-28-jun-3.pdf
Saved: petro_ncr_2025_feb-4-10-pdf.pdf
Saved: petro_ncr_2024-jan-25.pdf
Saved: petro_ncr_2023-mar-24-pdf.pdf
Saved: petro_ncr_2022-dec-29-pdf.pdf
Saved: petro_ncr_2024-sep-17-23-pdf.pdf
Saved: ncr-price-monitoring-11252025-pdf.pdf
Saved: petro_ncr_2023-feb-10-pdf.pdf
Saved: petro_ncr_2022-oct-06-pdf.pdf
Saved: petro_ncr_2023-apr-27.pdf
Saved: ncr-price-monitoring-03312026-pdf.pdf
Saved: petro_ncr_2022-feb-17-pdf.pdf
Saved: petro_ncr_2021-apr-15.pdf
Saved: petro_ncr_2024-apr-23-29.pdf
Saved: petro_ncr_2023-feb-03.pdf
Saved: petro_ncr_2021-sep-23-pdf.pdf
Saved: petro_ncr_2024-jul-9-15-pdf.pdf
Saved: petro_ncr_2022-mar-24-pdf.pdf
Saved: ncr-price-monitoring-03102026n-pdf.pdf
Saved: ncr-price-monitoring-12092025-pdf.pdf
Saved: petro_ncr_2023-nov-16-pdf.pdf
Saved: petro_ncr_2022-06-23.pdf
Saved: ncr-price-monitoring-01272026-pdf.pdf
Saved: petro_ncr_2021-mar-25.pdf
Saved: petro_ncr_2022-mar-31-pdf.pdf
Saved: petro_ncr_2025_mar-25-31-pdf.pdf
Saved: petro_ncr_2021-apr-01.pdf
Saved: petro_ncr_2022-aug-04-pdf.pdf
Saved: petro_ncr_2022-dec-15.pdf
Saved: petro_ncr_2024-nov-26-dec-2-pdf.pdf
Saved: petro_ncr_2023-jul-21-pdf.pdf
Saved: ncr-price-monitoring-01202026-pdf.pdf
Saved: ncr-price-monitoring-06102025-pdf.pdf
Saved: ncr-price-monitoring-12022025-pdf.pdf
Saved: ncr-price-monitoring-04292025-pdf.pdf
Saved: petro_ncr_2024-may-7-13-pdf.pdf
Saved: petro_ncr_2023-dec-14-pdf.pdf
Saved: petro_ncr_2023-feb-23-pdf.pdf
Saved: petro_ncr_2021-sep-09-pdf.pdf
Saved: ncr-price-monitoring-12232025-pdf.pdf
Saved: petro_ncr_2024-jul-30-aug-05-pdf.pdf
Saved: petro_ncr_2022-sep-15-pdf.pdf
Saved: petro_ncr_2022-jan-13-pdf.pdf
Saved: petro_ncr_2021-oct-07-pdf.pdf
Saved: petro_ncr_2024-jan-04.pdf
Saved: petro_ncr_2023-jan-20.pdf
Saved: petro_ncr_2023-aug-24-pdf.pdf
Saved: petro_ncr_2023-sep-21-update-pdf.pdf
Saved: ncr-price-monitoring-07222025-pdf.pdf
Saved: petro_ncr_2021-sep-30-pdf.pdf
Saved: petro_ncr_2023-aug-3-pdf.pdf
Saved: petro_ncr_2023-jan-12.pdf
Saved: petro_ncr_2021-may-27.pdf
Saved: petro_ncr_2023-mar-10-pdf.pdf
Saved: petro_ncr_2022-dec-22.pdf
Saved: petro_ncr_2024-dec-3-9-pdf.pdf
Saved: petro_ncr_2021-mar-18.pdf
Saved: petro_ncr_2023-nov-23-pdf.pdf
Saved: ncr-price-monitoring-10212025.pdf
Saved: ncr-price-monitoring-11182025-pdf.pdf
Saved: petro_ncr_2023-aug-11-pdf.pdf
Saved: petro_ncr_2022-mar-17-pdf.pdf
Saved: petro_ncr_2023-jun-01.pdf
Saved: petro_ncr_2024-jun-18-24.pdf
Saved: petro_ncr_2022-jan-27-pdf.pdf
Saved: petro_ncr_2023-oct-12-pdf.pdf
Saved: petro_ncr_2021-may-20-pdf.pdf
Saved: petro_ncr-2021-nov-04-pdf.pdf
Saved: petro_ncr_2021-aug-05-pdf.pdf
Saved: petro_ncr_2022-mar-10-pdf.pdf
Saved: petro_ncr_2023-nov-03-pdf.pdf
Saved: petro_ncr_2022-nov-17-pdf.pdf
Saved: petro_ncr_2021-july-01-pdf.pdf
Saved: petro_ncr_2021-may-06-pdf.pdf
Saved: petro_ncr_2024-apr-9-15.pdf
Saved: petro_ncr_2022-sep-06-pdf.pdf
Saved: petro_ncr_2024-dec-10-16-pdf.pdf
Saved: petro_ncr_2021-feb-11.pdf
Saved: petro_ncr_2021_jan_14.pdf
Saved: petro_ncr_2022-mar-03-pdf.pdf
Saved: petro_ncr_2025_apr-1-7-pdf.pdf
Saved: petro_ncr_2024-aug-13-19-pdf.pdf
Saved: petro_ncr_2024-may-14-20-pdf.pdf
Saved: petro_ncr_2022-apr-19.pdf
Saved: petro_ncr_2022-sep-23-pdf.pdf
Saved: petro_ncr_2025-jan-7-jan-13-pdf.pdf
Saved: petro_ncr_2023-mar-31-pdf.pdf
Saved: ncr-price-monitoring-12302025-pdf.pdf
Saved: petro_ncr_2022-aug-11-pdf.pdf
Saved: petro_ncr_2022-feb-10-pdf.pdf
Saved: petro_ncr_2021-june-03-pdf.pdf
Saved: petro_ncr_2021-dec-21-pdf.pdf
Saved: ncr-price-monitoring-03172026-pdf.pdf
Saved: petro_ncr_2022-jun-30.pdf
Saved: petro_ncr_2025_apr-8-14-pdf.pdf
Saved: petro_ncr_2023-jun-24.pdf
Saved: ncr-price-monitoring-09302025-pdf.pdf
Saved: petro_ncr_2023-may-06.pdf
Saved: petro_ncr_2022-jun-14-pdf.pdf
Saved: petro_ncr_2024-aug-20-26.pdf
Saved: petro_ncr-2021-oct-27-pdf.pdf
Saved: petro_ncr_2023-aug-31-pdf.pdf
Saved: petro_ncr_2024-nov-12-nov-18-pdf.pdf
Saved: petro_ncr_2022-feb-03-pdf.pdf
Saved: petro_ncr_2021-jul-08-pdf.pdf
Saved: petro_ncr_2022-aug-25-pdf.pdf
Saved: petro_ncr_2021_jan_06.pdf
Saved: ncr-price-monitoring-03242026-pdf.pdf
Saved: petro_ncr_2022-jul-14-1-pdf.pdf
Saved: petro_ncr_2021-feb-25.pdf
Saved: ncr-price-monitoring-11112025.pdf
Saved: ncr-price-monitoring-07152025-pdf.pdf
Saved: ncr-price-monitoring-03032026-pdf.pdf
Saved: petro_ncr_2023-dec-07-pdf.pdf
Saved: ncr-price-monitoring-10142025-pdf.pdf
Saved: petro_ncr_2024-feb-15.pdf
Saved: petro_ncr_2023-aug-17-pdf.pdf
Saved: petro_ncr_2023-jun-08.pdf
Saved: petro_ncr_2023-apr-09-pdf.pdf
Saved: petro_ncr_2022-jul-07.pdf
Saved: petro_ncr_2023-feb-17.pdf
Saved: petro_ncr_2022-may-26.pdf
Saved: petro_ncr_2023-jul-14-pdf.pdf
Saved: petro_ncr_2022-sep-29-pdf.pdf
Saved: petro_ncr_2021-june-17-pdf.pdf
Saved: petro_ncr_2022-oct-13_0-pdf.pdf
Saved: petro_ncr_2022-jun-09.pdf
Saved: petro_ncr_2021-sept-16-pdf-pdf.pdf
Saved: petro_ncr_2023-oct-05-updated-pdf.pdf
Saved: ncr-price-monitoring-06172025-pdf.pdf
Saved: petro_ncr_2021_feb_04.pdf
Saved: petro_ncr_2022-may-20-1.pdf
Saved: petro_ncr_2023-dec-28-pdf.pdf
Saved: priceadj_fuels_2024-feb-5-7.pdf
Saved: ncr-price-monitoring-10282025-pdf.pdf
Saved: petro_ncr-2021-nov-11-pdf.pdf
Saved: petro_ncr_2023-dec-22-pdf.pdf
Saved: petro_ncr_2022-jul-21-pdf.pdf
Saved: petro_ncr_2022-10-27-pdf.pdf
Saved: petro_ncr_2023-sep-14-pdf.pdf
Saved: petro_ncr_2024-jul-2-8-pdf.pdf
Saved: petro_ncr_2023-jan-26.pdf
Saved: petro_ncr_2023-nov-09-pdf.pdf
Saved: petro_ncr_2021-aug-19-pdf.pdf
Saved: petro_ncr_2024-nov-05-nov-11-pdf.pdf
Saved: petro_ncr_2025_feb-11-15-pdf.pdf
Saved: petro_ncr_2021-dec-10-pdf.pdf
Saved: petro_ncr_2021-aug-26-pdf.pdf
Saved: petro_ncr_2024-sep-10-16-pdf.pdf
Saved: petro_ncr_2024-mar-12.pdf
Saved: petro_ncr_2023-may-25.pdf
Saved: petro_ncr_2023-oct-26-pdf.pdf
Saved: petro_ncr_2024-mar-05.pdf
Saved: petro_ncr_2024-nov-19-nov-25-pdf.pdf
Saved: petro_ncr_2024-oct-08-14-pdf.pdf
Saved: petro_ncr_2023-jul-07-pdf.pdf
Saved: petro_ncr_2022-jan-20-pdf.pdf
Saved: petro_ncr_2021-may-13-pdf.pdf
Saved: petro_ncr_2022-nov-10-pdf.pdf
Saved: petro_ncr_2023-jun-29.pdf
Saved: petro_ncr_2021-sept-02_0-pdf.pdf
Saved: petro_ncr_2024-feb-27.pdf
Saved: petro_ncr_2022-nov-26-pdf.pdf
Saved: ncr-price-monitoring-09022025.pdf
Saved: petro_ncr_2023-jan-05.pdf
Saved: petro_ncr_2025_mar-18-24-pdf.pdf
Saved: ncr-price-monitoring-01132026-pdf.pdf
Saved: petro_ncr_2025_jan-28-feb-3-pdf.pdf
Saved: petro_ncr_2023-mar-17.pdf
Saved: ncr-price-monitoring-02242026-pdf.pdf
Saved: petro_ncr_2023-nov-30-pdf.pdf
Saved: ncr-price-monitoring-02172026-pdf.pdf
Saved: ncr-price-monitoring-01062026-pdf.pdf
Saved: petro_ncr_2024-may-21-27.pdf
Saved: ncr-price-monitoring-07-01-2025-pdf.pdf
Saved: ncr-price-monitoring-05062025-pdf.pdf
Saved: petro_ncr_2024-jun-04-10_0.pdf
Saved: petro_ncr_2025_feb-18-24-pdf.pdf
Saved: petro_ncr_2025-jan-14-jan-20-pdf.pdf
Saved: ncr-price-monitoring-07292025-pdf.pdf
Saved: ncr-price-monitoring-09232025.pdf
Saved: petro_ncr_2025-jan-21-jan-27-pdf.pdf
Saved: petro_ncr_2024-oct-1-7-pdf.pdf
Saved: petro_ncr_2024-dec-24-30-pdf.pdf
Saved: petro_ncr_2021-oct-21-pdf.pdf
Saved: petro_ncr_2021-june-24.pdf
Saved: petro_ncr_2023-apr-20.pdf
Saved: ncr-price-monitoring-11042025.pdf
Saved: petro_ncr-2022-oct-18-pdf.pdf
Saved: ncr-price-monitoring-05132025-pdf.pdf
Saved: petro_ncr_2022-may-05.pdf
Saved: petro_ncr_2022-nov-03-pdf.pdf
Saved: petro_ncr_2024-aug-06-12-pdf.pdf
Saved: petro_ncr_2024-jul-16-22_0-pdf.pdf
Saved: petro_ncr_2024-dec-17-23-pdf.pdf
Saved: petro_ncr_2024-sep-3-9-pdf.pdf
Saved: petro_ncr_2021-jul-28-pdf.pdf
Saved: ncr-price-monitoring-04072026-pdf.pdf
Saved: petro_ncr_2024-feb-01.pdf
Saved: petro_ncr_2025_mar-11-17-pdf.pdf
Saved: petro_ncr_2024-jan-09.pdf
Saved: _petro_ncr_2021-apr-29.pdf
Saved: ncr-price-monitoring-08192025-pdf.pdf
Saved: petro_ncr_2022-may-12.pdf
Saved: petro_ncr_2021-mar-11.pdf
Saved: petro_ncr_2021-jul-22-pdf.pdf
Saved: petro_ncr_2021_jan_21.pdf
Saved: ncr-price-monitoring-02102026-1-pdf.pdf
Saved: petro_ncr_2024-jul-23-29-pdf.pdf
Saved: petro_ncr_2024-jun-25-jul-1-pdf.pdf
Saved: petro_ncr_2023-jul-28-pdf.pdf
Saved: petro_ncr_2023-mar-02.pdf
Saved: petro_ncr_2022-dec-09.pdf
Saved: petro_ncr_2021-nov-30-dec-1-pdf.pdf
Saved: petro_ncr_2021-oct-14-pdf.pdf
Saved: petro_ncr_2020_dec_24-pdf.pdf
Saved: petro_ncr_2024-oct-29-nov-04-pdf.pdf
Saved: petro_ncr_2023-oct-17-updated-pdf.pdf
Saved: ncr-price-monitoring-08262025.pdf
Saved: petro_ncr_2024-apr-16-22.pdf
Saved: _petro_ncr_2021-june-10.pdf
Saved: petro_ncr_2023-may-12.pdf
Saved: petro_ncr_2024-oct-22-28-pdf.pdf
Saved: ncr-price-monitoring-07082025-pdf.pdf
Saved: ncr-price-monitoring-10072025-pdf.pdf
Saved: ncr-price-monitoring-06242025-pdf.pdf
Saved: petro_ncr_2024-jun-11-17-pdf.pdf
Saved: petro_ncr_2022-sep-01.pdf
Saved: petro_ncr_2024-sep-24-30-pdf.pdf
Saved: petro_ncr_2024-aug-27-sep-2-pdf.pdf
Saved: petro_ncr_2022-feb-24-pdf.pdf
Saved: ncr-price-monitoring-02032026-pdf.pdf
Saved: petro_ncr_2022-aug-18-pdf.pdf
Saved: petro_ncr_2024-mar-26-apr-1.pdf
Saved: petro_ncr_2024-apr-30-may-6-pdf.pdf
Saved: petro_ncr_2023-apr-13.pdf
Saved: petro_ncr_2022-jul-28-pdf.pdf
Saved: petro_ncr_2022-jun-02.pdf
Saved: petro_ncr_2022-apr-28.pdf
Saved: petro_ncr_2023-may-19.pdf
Saved: petro_ncr_2022-jan-02-pdf.pdf
Saved: ncr-price-monitoring-09092025-pdf.pdf
Saved: petro_ncr_2021-nov-18-pdf.pdf
Saved: petro_ncr_2021-nov-25-pdf.pdf
Saved: petro_ncr_2021-aug-12-pdf.pdf
Saved: petro_ncr_2021-apr-08.pdf
Saved: petro_ncr_2021_jan_28.pdf
Saved: petro_ncr_2022-dec-03.pdf
Saved: petro_ncr_2022-jan-06-pdf.pdf
Saved: petro_ncr_2020_dec_30.pdf
Saved: petro_ncr_2024-oct-15-21-pdf.pdf
Saved: ncr-price-monitoring-04152025-pdf.pdf
Saved: petro_ncr_2024-jan-16.pdf
Saved: petro_ncr_2023-jun-15.pdf
DOE PDF extraction complete.

### 1.3 Renaming DOE Files

In [5]:
utils.standardize_doe_date(data_folder='data/uncleaned_data/doe_pdf')

  -> Renamed: ncr-price-monitoring-01062026-pdf.pdf  ==>  2026-01-06.pdf
  -> Renamed: ncr-price-monitoring-01132026-pdf.pdf  ==>  2026-01-13.pdf
  -> Renamed: ncr-price-monitoring-01202026-pdf.pdf  ==>  2026-01-20.pdf
  -> Renamed: ncr-price-monitoring-01272026-pdf.pdf  ==>  2026-01-27.pdf
  -> Renamed: ncr-price-monitoring-02032026-pdf.pdf  ==>  2026-02-03.pdf
  -> Renamed: ncr-price-monitoring-02102026-1-pdf.pdf  ==>  2026-02-10.pdf
  -> Renamed: ncr-price-monitoring-02172026-pdf.pdf  ==>  2026-02-17.pdf
  -> Renamed: ncr-price-monitoring-02242026-pdf.pdf  ==>  2026-02-24.pdf
  -> Renamed: ncr-price-monitoring-03032026-pdf.pdf  ==>  2026-03-03.pdf
  -> Renamed: ncr-price-monitoring-03102026n-pdf.pdf  ==>  2026-03-10.pdf
  -> Renamed: ncr-price-monitoring-03172026-pdf.pdf  ==>  2026-03-17.pdf
  -> Renamed: ncr-price-monitoring-03242026-pdf.pdf  ==>  2026-03-24.pdf
  -> Renamed: ncr-price-monitoring-03312026-pdf.pdf  ==>  2026-03-31.pdf
  -> Renamed: ncr-price-monitoring-04072026-pdf.pdf  ==>  2026-04-07.pdf
  -> Renamed: ncr-price-monitoring-04152025-pdf.pdf  ==>  2025-04-15.pdf
  -> Renamed: ncr-price-monitoring-04222025-pdf.pdf  ==>  2025-04-22.pdf
  -> Renamed: ncr-price-monitoring-04292025-pdf.pdf  ==>  2025-04-29.pdf
  -> Renamed: ncr-price-monitoring-05062025-pdf.pdf  ==>  2025-05-06.pdf
  -> Renamed: ncr-price-monitoring-05132025-pdf.pdf  ==>  2025-05-13.pdf
  -> Renamed: ncr-price-monitoring-05202025-pdf.pdf  ==>  2025-05-20.pdf
  -> Renamed: ncr-price-monitoring-06102025-pdf.pdf  ==>  2025-06-10.pdf
  -> Renamed: ncr-price-monitoring-06172025-pdf.pdf  ==>  2025-06-17.pdf
  -> Renamed: ncr-price-monitoring-06242025-pdf.pdf  ==>  2025-06-24.pdf
  -> Renamed: ncr-price-monitoring-07-01-2025-pdf.pdf  ==>  2025-07-01.pdf
  -> Renamed: ncr-price-monitoring-07082025-pdf.pdf  ==>  2025-07-08.pdf
  -> Renamed: ncr-price-monitoring-07152025-pdf.pdf  ==>  2025-07-15.pdf
  -> Renamed: ncr-price-monitoring-07222025-pdf.pdf  ==>  2025-07-22.pdf
  -> Renamed: ncr-price-monitoring-07292025-pdf.pdf  ==>  2025-07-29.pdf
  -> Renamed: ncr-price-monitoring-08052025-pdf.pdf  ==>  2025-08-05.pdf
  -> Renamed: ncr-price-monitoring-08122025-pdf.pdf  ==>  2025-08-12.pdf
  -> Renamed: ncr-price-monitoring-08192025-pdf.pdf  ==>  2025-08-19.pdf
  -> Renamed: ncr-price-monitoring-08262025.pdf  ==>  2025-08-26.pdf
  -> Renamed: ncr-price-monitoring-09022025.pdf  ==>  2025-09-02.pdf
  -> Renamed: ncr-price-monitoring-09092025-pdf.pdf  ==>  2025-09-09.pdf
  -> Renamed: ncr-price-monitoring-09162025-pdf.pdf  ==>  2025-09-16.pdf
  -> Renamed: ncr-price-monitoring-09232025.pdf  ==>  2025-09-23.pdf
  -> Renamed: ncr-price-monitoring-09302025-pdf.pdf  ==>  2025-09-30.pdf
  -> Renamed: ncr-price-monitoring-10072025-pdf.pdf  ==>  2025-10-07.pdf
  -> Renamed: ncr-price-monitoring-10142025-pdf.pdf  ==>  2025-10-14.pdf
  -> Renamed: ncr-price-monitoring-10212025.pdf  ==>  2025-10-21.pdf
  -> Renamed: ncr-price-monitoring-10282025-pdf.pdf  ==>  2025-10-28.pdf
  -> Renamed: ncr-price-monitoring-11042025.pdf  ==>  2025-11-04.pdf
  -> Renamed: ncr-price-monitoring-11112025.pdf  ==>  2025-11-11.pdf
  -> Renamed: ncr-price-monitoring-11182025-pdf.pdf  ==>  2025-11-18.pdf
  -> Renamed: ncr-price-monitoring-11252025-pdf.pdf  ==>  2025-11-25.pdf
  -> Renamed: ncr-price-monitoring-12022025-pdf.pdf  ==>  2025-12-02.pdf
  -> Renamed: ncr-price-monitoring-12092025-pdf.pdf  ==>  2025-12-09.pdf
  -> Renamed: ncr-price-monitoring-12162025-pdf.pdf  ==>  2025-12-16.pdf
  -> Renamed: ncr-price-monitoring-12232025-pdf.pdf  ==>  2025-12-23.pdf
  -> Renamed: ncr-price-monitoring-12302025-pdf.pdf  ==>  2025-12-30.pdf
  -> Renamed: petro_ncr-2021-nov-04-pdf.pdf  ==>  2021-11-04.pdf
  -> Renamed: petro_ncr-2021-nov-11-pdf.pdf  ==>  2021-11-11.pdf
  -> Renamed: petro_ncr-2021-oct-27-pdf.pdf  ==>  2021-10-27.pdf
  -> Renamed: petro_ncr-2022-oct-18-pdf.pdf  ==>  2022-10-18.pdf
  -> Renamed: petro_ncr_2020_dec_24-pdf.pdf  ==>  2020-12-24.pdf
  -> Renamed: petro_ncr_2020_dec_30.pdf  ==>  2020-12-30.pdf
  -> Renamed: petro_ncr_2021-apr-01.pdf  ==>  2021-04-01.pdf
  -> Renamed: petro_ncr_2021-apr-08.pdf  ==>  2021-04-08.pdf
  -> Renamed: petro_ncr_2021-apr-15.pdf  ==>  2021-04-15.pdf
  -> Renamed: petro_ncr_2021-aug-05-pdf.pdf  ==>  2021-08-05.pdf
  -> Renamed: petro_ncr_2021-aug-12-pdf.pdf  ==>  2021-08-12.pdf
  -> Renamed: petro_ncr_2021-aug-19-pdf.pdf  ==>  2021-08-19.pdf
  -> Renamed: petro_ncr_2021-aug-26-pdf.pdf  ==>  2021-08-26.pdf
  -> Renamed: petro_ncr_2021-dec-10-pdf.pdf  ==>  2021-12-10.pdf
  -> Renamed: petro_ncr_2021-dec-16_0-pdf.pdf  ==>  2021-12-16.pdf
  -> Renamed: petro_ncr_2021-dec-21-pdf.pdf  ==>  2021-12-21.pdf
  -> Renamed: petro_ncr_2021-feb-11.pdf  ==>  2021-02-11.pdf
  -> Renamed: petro_ncr_2021-feb-18.pdf  ==>  2021-02-18.pdf
  -> Renamed: petro_ncr_2021-feb-25.pdf  ==>  2021-02-25.pdf
  -> Renamed: petro_ncr_2021-jul-08-pdf.pdf  ==>  2021-07-08.pdf
  -> Renamed: petro_ncr_2021-jul-15-pdf.pdf  ==>  2021-07-15.pdf
  -> Renamed: petro_ncr_2021-jul-22-pdf.pdf  ==>  2021-07-22.pdf
  -> Renamed: petro_ncr_2021-jul-28-pdf.pdf  ==>  2021-07-28.pdf
  -> Renamed: petro_ncr_2021-july-01-pdf.pdf  ==>  2021-07-01.pdf
  -> Renamed: petro_ncr_2021-june-03-pdf.pdf  ==>  2021-06-03.pdf
  -> Renamed: petro_ncr_2021-june-17-pdf.pdf  ==>  2021-06-17.pdf
  -> Renamed: petro_ncr_2021-june-24.pdf  ==>  2021-06-24.pdf
  -> Renamed: petro_ncr_2021-mar-11.pdf  ==>  2021-03-11.pdf
  -> Renamed: petro_ncr_2021-mar-18.pdf  ==>  2021-03-18.pdf
  -> Renamed: petro_ncr_2021-mar-25.pdf  ==>  2021-03-25.pdf
  -> Renamed: petro_ncr_2021-may-06-pdf.pdf  ==>  2021-05-06.pdf
  -> Renamed: petro_ncr_2021-may-13-pdf.pdf  ==>  2021-05-13.pdf
  -> Renamed: petro_ncr_2021-may-20-pdf.pdf  ==>  2021-05-20.pdf
  -> Renamed: petro_ncr_2021-may-27.pdf  ==>  2021-05-27.pdf
  -> Renamed: petro_ncr_2021-nov-18-pdf.pdf  ==>  2021-11-18.pdf
  -> Renamed: petro_ncr_2021-nov-25-pdf.pdf  ==>  2021-11-25.pdf
  -> Renamed: petro_ncr_2021-nov-30-dec-1-pdf.pdf  ==>  2021-11-30.pdf
  -> Renamed: petro_ncr_2021-oct-07-pdf.pdf  ==>  2021-10-07.pdf
  -> Renamed: petro_ncr_2021-oct-14-pdf.pdf  ==>  2021-10-14.pdf
  -> Renamed: petro_ncr_2021-oct-21-pdf.pdf  ==>  2021-10-21.pdf
  -> Renamed: petro_ncr_2021-sep-09-pdf.pdf  ==>  2021-09-09.pdf
  -> Renamed: petro_ncr_2021-sep-23-pdf.pdf  ==>  2021-09-23.pdf
  -> Renamed: petro_ncr_2021-sep-30-pdf.pdf  ==>  2021-09-30.pdf
  -> Renamed: petro_ncr_2021-sept-02_0-pdf.pdf  ==>  2021-09-02.pdf
  -> Renamed: petro_ncr_2021-sept-16-pdf-pdf.pdf  ==>  2021-09-16.pdf
  -> Renamed: petro_ncr_2021_feb_04.pdf  ==>  2021-02-04.pdf
  -> Renamed: petro_ncr_2021_jan_06.pdf  ==>  2021-01-06.pdf
  -> Renamed: petro_ncr_2021_jan_14.pdf  ==>  2021-01-14.pdf
  -> Renamed: petro_ncr_2021_jan_21.pdf  ==>  2021-01-21.pdf
  -> Renamed: petro_ncr_2021_jan_28.pdf  ==>  2021-01-28.pdf
  -> Renamed: petro_ncr_2022-06-23.pdf  ==>  2022-06-23.pdf
  -> Renamed: petro_ncr_2022-10-27-pdf.pdf  ==>  2022-10-27.pdf
  -> Renamed: petro_ncr_2022-apr-07.pdf  ==>  2022-04-07.pdf
  -> Renamed: petro_ncr_2022-apr-15.pdf  ==>  2022-04-15.pdf
  -> Renamed: petro_ncr_2022-apr-19.pdf  ==>  2022-04-19.pdf
  -> Renamed: petro_ncr_2022-apr-28.pdf  ==>  2022-04-28.pdf
  -> Renamed: petro_ncr_2022-aug-04-pdf.pdf  ==>  2022-08-04.pdf
  -> Renamed: petro_ncr_2022-aug-11-pdf.pdf  ==>  2022-08-11.pdf
  -> Renamed: petro_ncr_2022-aug-18-pdf.pdf  ==>  2022-08-18.pdf
  -> Renamed: petro_ncr_2022-aug-25-pdf.pdf  ==>  2022-08-25.pdf
  -> Renamed: petro_ncr_2022-dec-03.pdf  ==>  2022-12-03.pdf
  -> Renamed: petro_ncr_2022-dec-09.pdf  ==>  2022-12-09.pdf
  -> Renamed: petro_ncr_2022-dec-15.pdf  ==>  2022-12-15.pdf
  -> Renamed: petro_ncr_2022-dec-22.pdf  ==>  2022-12-22.pdf
  -> Renamed: petro_ncr_2022-dec-29-pdf.pdf  ==>  2022-12-29.pdf
  -> Renamed: petro_ncr_2022-feb-03-pdf.pdf  ==>  2022-02-03.pdf
  -> Renamed: petro_ncr_2022-feb-10-pdf.pdf  ==>  2022-02-10.pdf
  -> Renamed: petro_ncr_2022-feb-17-pdf.pdf  ==>  2022-02-17.pdf
  -> Renamed: petro_ncr_2022-feb-24-pdf.pdf  ==>  2022-02-24.pdf
  -> Renamed: petro_ncr_2022-jan-02-pdf.pdf  ==>  2022-01-02.pdf
  -> Renamed: petro_ncr_2022-jan-06-pdf.pdf  ==>  2022-01-06.pdf
  -> Renamed: petro_ncr_2022-jan-13-pdf.pdf  ==>  2022-01-13.pdf
  -> Renamed: petro_ncr_2022-jan-20-pdf.pdf  ==>  2022-01-20.pdf
  -> Renamed: petro_ncr_2022-jan-27-pdf.pdf  ==>  2022-01-27.pdf
  -> Renamed: petro_ncr_2022-jul-07.pdf  ==>  2022-07-07.pdf
  -> Renamed: petro_ncr_2022-jul-14-1-pdf.pdf  ==>  2022-07-14.pdf
  -> Renamed: petro_ncr_2022-jul-21-pdf.pdf  ==>  2022-07-21.pdf
  -> Renamed: petro_ncr_2022-jul-28-pdf.pdf  ==>  2022-07-28.pdf
  -> Renamed: petro_ncr_2022-jun-02.pdf  ==>  2022-06-02.pdf
  -> Renamed: petro_ncr_2022-jun-09.pdf  ==>  2022-06-09.pdf
  -> Renamed: petro_ncr_2022-jun-14-pdf.pdf  ==>  2022-06-14.pdf
  -> Renamed: petro_ncr_2022-jun-30.pdf  ==>  2022-06-30.pdf
  -> Renamed: petro_ncr_2022-mar-03-pdf.pdf  ==>  2022-03-03.pdf
  -> Renamed: petro_ncr_2022-mar-10-pdf.pdf  ==>  2022-03-10.pdf
  -> Renamed: petro_ncr_2022-mar-17-pdf.pdf  ==>  2022-03-17.pdf
  -> Renamed: petro_ncr_2022-mar-24-pdf.pdf  ==>  2022-03-24.pdf
  -> Renamed: petro_ncr_2022-mar-31-pdf.pdf  ==>  2022-03-31.pdf
  -> Renamed: petro_ncr_2022-may-05.pdf  ==>  2022-05-05.pdf
  -> Renamed: petro_ncr_2022-may-12.pdf  ==>  2022-05-12.pdf
  -> Renamed: petro_ncr_2022-may-20-1.pdf  ==>  2022-05-20.pdf
  -> Renamed: petro_ncr_2022-may-26.pdf  ==>  2022-05-26.pdf
  -> Renamed: petro_ncr_2022-nov-03-pdf.pdf  ==>  2022-11-03.pdf
  -> Renamed: petro_ncr_2022-nov-10-pdf.pdf  ==>  2022-11-10.pdf
  -> Renamed: petro_ncr_2022-nov-17-pdf.pdf  ==>  2022-11-17.pdf
  -> Renamed: petro_ncr_2022-nov-26-pdf.pdf  ==>  2022-11-26.pdf
  -> Renamed: petro_ncr_2022-oct-06-pdf.pdf  ==>  2022-10-06.pdf
  -> Renamed: petro_ncr_2022-oct-13_0-pdf.pdf  ==>  2022-10-13.pdf
  -> Renamed: petro_ncr_2022-sep-01.pdf  ==>  2022-09-01.pdf
  -> Renamed: petro_ncr_2022-sep-06-pdf.pdf  ==>  2022-09-06.pdf
  -> Renamed: petro_ncr_2022-sep-15-pdf.pdf  ==>  2022-09-15.pdf
  -> Renamed: petro_ncr_2022-sep-23-pdf.pdf  ==>  2022-09-23.pdf
  -> Renamed: petro_ncr_2022-sep-29-pdf.pdf  ==>  2022-09-29.pdf
  -> Renamed: petro_ncr_2023-apr-09-pdf.pdf  ==>  2023-04-09.pdf
  -> Renamed: petro_ncr_2023-apr-13.pdf  ==>  2023-04-13.pdf
  -> Renamed: petro_ncr_2023-apr-20.pdf  ==>  2023-04-20.pdf
  -> Renamed: petro_ncr_2023-apr-27.pdf  ==>  2023-04-27.pdf
  -> Renamed: petro_ncr_2023-aug-11-pdf.pdf  ==>  2023-08-11.pdf
  -> Renamed: petro_ncr_2023-aug-17-pdf.pdf  ==>  2023-08-17.pdf
  -> Renamed: petro_ncr_2023-aug-24-pdf.pdf  ==>  2023-08-24.pdf
  -> Renamed: petro_ncr_2023-aug-3-pdf.pdf  ==>  2023-08-03.pdf
  -> Renamed: petro_ncr_2023-aug-31-pdf.pdf  ==>  2023-08-31.pdf
  -> Renamed: petro_ncr_2023-dec-07-pdf.pdf  ==>  2023-12-07.pdf
  -> Renamed: petro_ncr_2023-dec-14-pdf.pdf  ==>  2023-12-14.pdf
  -> Renamed: petro_ncr_2023-dec-22-pdf.pdf  ==>  2023-12-22.pdf
  -> Renamed: petro_ncr_2023-dec-28-pdf.pdf  ==>  2023-12-28.pdf
  -> Renamed: petro_ncr_2023-feb-03.pdf  ==>  2023-02-03.pdf
  -> Renamed: petro_ncr_2023-feb-10-pdf.pdf  ==>  2023-02-10.pdf
  -> Renamed: petro_ncr_2023-feb-17.pdf  ==>  2023-02-17.pdf
  -> Renamed: petro_ncr_2023-feb-23-pdf.pdf  ==>  2023-02-23.pdf
  -> Renamed: petro_ncr_2023-jan-05.pdf  ==>  2023-01-05.pdf
  -> Renamed: petro_ncr_2023-jan-12.pdf  ==>  2023-01-12.pdf
  -> Renamed: petro_ncr_2023-jan-20.pdf  ==>  2023-01-20.pdf
  -> Renamed: petro_ncr_2023-jan-26.pdf  ==>  2023-01-26.pdf
  -> Renamed: petro_ncr_2023-jul-07-pdf.pdf  ==>  2023-07-07.pdf
  -> Renamed: petro_ncr_2023-jul-14-pdf.pdf  ==>  2023-07-14.pdf
  -> Renamed: petro_ncr_2023-jul-21-pdf.pdf  ==>  2023-07-21.pdf
  -> Renamed: petro_ncr_2023-jul-28-pdf.pdf  ==>  2023-07-28.pdf
  -> Renamed: petro_ncr_2023-jun-01.pdf  ==>  2023-06-01.pdf
  -> Renamed: petro_ncr_2023-jun-08.pdf  ==>  2023-06-08.pdf
  -> Renamed: petro_ncr_2023-jun-15.pdf  ==>  2023-06-15.pdf
  -> Renamed: petro_ncr_2023-jun-24.pdf  ==>  2023-06-24.pdf
  -> Renamed: petro_ncr_2023-jun-29.pdf  ==>  2023-06-29.pdf
  -> Renamed: petro_ncr_2023-mar-02.pdf  ==>  2023-03-02.pdf
  -> Renamed: petro_ncr_2023-mar-10-pdf.pdf  ==>  2023-03-10.pdf
  -> Renamed: petro_ncr_2023-mar-17.pdf  ==>  2023-03-17.pdf
  -> Renamed: petro_ncr_2023-mar-24-pdf.pdf  ==>  2023-03-24.pdf
  -> Renamed: petro_ncr_2023-mar-31-pdf.pdf  ==>  2023-03-31.pdf
  -> Renamed: petro_ncr_2023-may-06.pdf  ==>  2023-05-06.pdf
  -> Renamed: petro_ncr_2023-may-12.pdf  ==>  2023-05-12.pdf
  -> Renamed: petro_ncr_2023-may-19.pdf  ==>  2023-05-19.pdf
  -> Renamed: petro_ncr_2023-may-25.pdf  ==>  2023-05-25.pdf
  -> Renamed: petro_ncr_2023-nov-03-pdf.pdf  ==>  2023-11-03.pdf
  -> Renamed: petro_ncr_2023-nov-09-pdf.pdf  ==>  2023-11-09.pdf
  -> Renamed: petro_ncr_2023-nov-16-pdf.pdf  ==>  2023-11-16.pdf
  -> Renamed: petro_ncr_2023-nov-23-pdf.pdf  ==>  2023-11-23.pdf
  -> Renamed: petro_ncr_2023-nov-30-pdf.pdf  ==>  2023-11-30.pdf
  -> Renamed: petro_ncr_2023-oct-05-updated-pdf.pdf  ==>  2023-10-05.pdf
  -> Renamed: petro_ncr_2023-oct-12-pdf.pdf  ==>  2023-10-12.pdf
  -> Renamed: petro_ncr_2023-oct-17-updated-pdf.pdf  ==>  2023-10-17.pdf
  -> Renamed: petro_ncr_2023-oct-26-pdf.pdf  ==>  2023-10-26.pdf
  -> Renamed: petro_ncr_2023-sep-14-pdf.pdf  ==>  2023-09-14.pdf
  -> Renamed: petro_ncr_2023-sep-21-update-pdf.pdf  ==>  2023-09-21.pdf
  -> Renamed: petro_ncr_2023-sep-28-pdf.pdf  ==>  2023-09-28.pdf
  -> Renamed: petro_ncr_2024-apr-16-22.pdf  ==>  2024-04-16.pdf
  -> Renamed: petro_ncr_2024-apr-2-8.pdf  ==>  2024-04-02.pdf
  -> Renamed: petro_ncr_2024-apr-23-29.pdf  ==>  2024-04-23.pdf
  -> Renamed: petro_ncr_2024-apr-30-may-6-pdf.pdf  ==>  2024-04-30.pdf
  -> Renamed: petro_ncr_2024-apr-9-15.pdf  ==>  2024-04-09.pdf
  -> Renamed: petro_ncr_2024-aug-06-12-pdf.pdf  ==>  2024-08-06.pdf
  -> Renamed: petro_ncr_2024-aug-13-19-pdf.pdf  ==>  2024-08-13.pdf
  -> Renamed: petro_ncr_2024-aug-20-26.pdf  ==>  2024-08-20.pdf
  -> Renamed: petro_ncr_2024-aug-27-sep-2-pdf.pdf  ==>  2024-08-27.pdf
  -> Renamed: petro_ncr_2024-dec-10-16-pdf.pdf  ==>  2024-12-10.pdf
  -> Renamed: petro_ncr_2024-dec-17-23-pdf.pdf  ==>  2024-12-17.pdf
  -> Renamed: petro_ncr_2024-dec-24-30-pdf.pdf  ==>  2024-12-24.pdf
  -> Renamed: petro_ncr_2024-dec-3-9-pdf.pdf  ==>  2024-12-03.pdf
  -> Renamed: petro_ncr_2024-feb-01.pdf  ==>  2024-02-01.pdf
  -> Renamed: petro_ncr_2024-feb-15.pdf  ==>  2024-02-15.pdf
  -> Renamed: petro_ncr_2024-feb-27.pdf  ==>  2024-02-27.pdf
  -> Renamed: petro_ncr_2024-jan-04.pdf  ==>  2024-01-04.pdf
  -> Renamed: petro_ncr_2024-jan-09.pdf  ==>  2024-01-09.pdf
  -> Renamed: petro_ncr_2024-jan-16.pdf  ==>  2024-01-16.pdf
  -> Renamed: petro_ncr_2024-jan-25.pdf  ==>  2024-01-25.pdf
  -> Renamed: petro_ncr_2024-jul-16-22_0-pdf.pdf  ==>  2024-07-16.pdf
  -> Renamed: petro_ncr_2024-jul-2-8-pdf.pdf  ==>  2024-07-02.pdf
  -> Renamed: petro_ncr_2024-jul-23-29-pdf.pdf  ==>  2024-07-23.pdf
  -> Renamed: petro_ncr_2024-jul-30-aug-05-pdf.pdf  ==>  2024-07-30.pdf
  -> Renamed: petro_ncr_2024-jul-9-15-pdf.pdf  ==>  2024-07-09.pdf
  -> Renamed: petro_ncr_2024-jun-04-10_0.pdf  ==>  2024-06-04.pdf
  -> Renamed: petro_ncr_2024-jun-11-17-pdf.pdf  ==>  2024-06-11.pdf
  -> Renamed: petro_ncr_2024-jun-18-24.pdf  ==>  2024-06-18.pdf
  -> Renamed: petro_ncr_2024-jun-25-jul-1-pdf.pdf  ==>  2024-06-25.pdf
  -> Renamed: petro_ncr_2024-mar-05.pdf  ==>  2024-03-05.pdf
  -> Renamed: petro_ncr_2024-mar-12.pdf  ==>  2024-03-12.pdf
  -> Renamed: petro_ncr_2024-mar-19.pdf  ==>  2024-03-19.pdf
  -> Renamed: petro_ncr_2024-mar-26-apr-1.pdf  ==>  2024-03-26.pdf
  -> Renamed: petro_ncr_2024-may-14-20-pdf.pdf  ==>  2024-05-14.pdf
  -> Renamed: petro_ncr_2024-may-21-27.pdf  ==>  2024-05-21.pdf
  -> Renamed: petro_ncr_2024-may-28-jun-3.pdf  ==>  2024-05-28.pdf
  -> Renamed: petro_ncr_2024-may-7-13-pdf.pdf  ==>  2024-05-07.pdf
  -> Renamed: petro_ncr_2024-nov-05-nov-11-pdf.pdf  ==>  2024-11-05.pdf
  -> Renamed: petro_ncr_2024-nov-12-nov-18-pdf.pdf  ==>  2024-11-12.pdf
  -> Renamed: petro_ncr_2024-nov-19-nov-25-pdf.pdf  ==>  2024-11-19.pdf
  -> Renamed: petro_ncr_2024-nov-26-dec-2-pdf.pdf  ==>  2024-11-26.pdf
  -> Renamed: petro_ncr_2024-oct-08-14-pdf.pdf  ==>  2024-10-08.pdf
  -> Renamed: petro_ncr_2024-oct-1-7-pdf.pdf  ==>  2024-10-01.pdf
  -> Renamed: petro_ncr_2024-oct-15-21-pdf.pdf  ==>  2024-10-15.pdf
  -> Renamed: petro_ncr_2024-oct-22-28-pdf.pdf  ==>  2024-10-22.pdf
  -> Renamed: petro_ncr_2024-oct-29-nov-04-pdf.pdf  ==>  2024-10-29.pdf
  -> Renamed: petro_ncr_2024-sep-10-16-pdf.pdf  ==>  2024-09-10.pdf
  -> Renamed: petro_ncr_2024-sep-17-23-pdf.pdf  ==>  2024-09-17.pdf
  -> Renamed: petro_ncr_2024-sep-24-30-pdf.pdf  ==>  2024-09-24.pdf
  -> Renamed: petro_ncr_2024-sep-3-9-pdf.pdf  ==>  2024-09-03.pdf
  -> Renamed: petro_ncr_2025-jan-14-jan-20-pdf.pdf  ==>  2025-01-14.pdf
  -> Renamed: petro_ncr_2025-jan-21-jan-27-pdf.pdf  ==>  2025-01-21.pdf
  -> Renamed: petro_ncr_2025-jan-7-jan-13-pdf.pdf  ==>  2025-01-07.pdf
  -> Renamed: petro_ncr_2025_apr-1-7-pdf.pdf  ==>  2025-04-01.pdf
  -> Renamed: petro_ncr_2025_apr-8-14-pdf.pdf  ==>  2025-04-08.pdf
  -> Renamed: petro_ncr_2025_feb-11-15-pdf.pdf  ==>  2025-02-11.pdf
  -> Renamed: petro_ncr_2025_feb-18-24-pdf.pdf  ==>  2025-02-18.pdf
  -> Renamed: petro_ncr_2025_feb-25-mar-3-pdf.pdf  ==>  2025-02-25.pdf
  -> Renamed: petro_ncr_2025_feb-4-10-pdf.pdf  ==>  2025-02-04.pdf
  -> Renamed: petro_ncr_2025_jan-28-feb-3-pdf.pdf  ==>  2025-01-28.pdf
  -> Renamed: petro_ncr_2025_mar-11-17-pdf.pdf  ==>  2025-03-11.pdf
  -> Renamed: petro_ncr_2025_mar-18-24-pdf.pdf  ==>  2025-03-18.pdf
  -> Renamed: petro_ncr_2025_mar-25-31-pdf.pdf  ==>  2025-03-25.pdf
  -> Renamed: petro_ncr_2025_mar-4-10-pdf.pdf  ==>  2025-03-04.pdf
  -> Renamed: priceadj_fuels_2024-feb-5-7.pdf  ==>  2024-02-05.pdf
  -> Renamed: _petro_ncr_2021-apr-29.pdf  ==>  2021-04-29.pdf
  -> Renamed: _petro_ncr_2021-june-10.pdf  ==>  2021-06-10.pdf
Renamed 270 files.

In [6]:
df_doe = utils.extract_all_pdfs('data/uncleaned_data/doe_pdf')

output_csv = 'data/semi_cleaned_data/DOE_NCR_OilPrices_Compiled.csv'
utils.save_csv(df_doe, output_csv)

Found 270 PDF(s) in 'data\uncleaned_data\doe_pdf'
  [1/270] 2020-12-24.pdf — 298 rows
  [2/270] 2020-12-30.pdf — 296 rows
  [3/270] 2021-01-06.pdf — 303 rows
  [4/270] 2021-01-14.pdf — 309 rows
  [5/270] 2021-01-21.pdf — 308 rows
  [6/270] 2021-01-28.pdf — 308 rows
  [7/270] 2021-02-04.pdf — 308 rows
  [8/270] 2021-02-11.pdf — 352 rows
  [9/270] 2021-02-18.pdf — 352 rows
  [10/270] 2021-02-25.pdf — 308 rows
  [11/270] 2021-03-11.pdf — 353 rows
  [12/270] 2021-03-18.pdf — 308 rows
  [13/270] 2021-03-25.pdf — 353 rows
  [14/270] 2021-04-01.pdf — 307 rows
  [15/270] 2021-04-08.pdf — 312 rows
  [16/270] 2021-04-15.pdf — 358 rows
  [17/270] 2021-04-29.pdf — 358 rows
  [18/270] 2021-05-06.pdf — 319 rows
  [19/270] 2021-05-13.pdf — 319 rows
  [20/270] 2021-05-20.pdf — 319 rows
  [21/270] 2021-05-27.pdf — 319 rows
  [22/270] 2021-06-03.pdf — 363 rows
  [23/270] 2021-06-10.pdf — 354 rows
  [24/270] 2021-06-17.pdf — 351 rows
  [25/270] 2021-06-24.pdf — 352 rows
  [26/270] 2021-07-01.pdf — 357 rows
  [27/270] 2021-07-08.pdf — 365 rows
  [28/270] 2021-07-15.pdf — 354 rows
  [29/270] 2021-07-22.pdf — 403 rows
  [30/270] 2021-07-28.pdf — 361 rows
  [31/270] 2021-08-05.pdf — 354 rows
  [32/270] 2021-08-12.pdf — 356 rows
  [33/270] 2021-08-19.pdf — 405 rows
  [34/270] 2021-08-26.pdf — 272 rows
  [35/270] 2021-09-02.pdf — 270 rows
  [36/270] 2021-09-09.pdf — 375 rows
  [37/270] 2021-09-16.pdf — 272 rows
  [38/270] 2021-09-23.pdf — 270 rows
  [39/270] 2021-09-30.pdf — 270 rows
  [40/270] 2021-10-07.pdf — 367 rows
  [41/270] 2021-10-14.pdf — 367 rows
  [42/270] 2021-10-21.pdf — 0 rows
  [43/270] 2021-10-27.pdf — 368 rows
  [44/270] 2021-11-04.pdf — 267 rows
  [45/270] 2021-11-11.pdf — 277 rows
  [46/270] 2021-11-18.pdf — 277 rows
  [47/270] 2021-11-25.pdf — 277 rows
  [48/270] 2021-11-30.pdf — 278 rows
  [49/270] 2021-12-10.pdf — 278 rows
  [50/270] 2021-12-16.pdf — 278 rows
  [51/270] 2021-12-21.pdf — 375 rows
  [52/270] 2022-01-02.pdf — 376 rows
  [53/270] 2022-01-06.pdf — 278 rows
  [54/270] 2022-01-13.pdf — 377 rows
  [55/270] 2022-01-20.pdf — 377 rows
  [56/270] 2022-01-27.pdf — 377 rows
  [57/270] 2022-02-03.pdf — 388 rows
  [58/270] 2022-02-10.pdf — 285 rows
  [59/270] 2022-02-17.pdf — 387 rows
  [60/270] 2022-02-24.pdf — 388 rows
  [61/270] 2022-03-03.pdf — 282 rows
  [62/270] 2022-03-10.pdf — 383 rows
  [63/270] 2022-03-17.pdf — 276 rows
  [64/270] 2022-03-24.pdf — 385 rows
  [65/270] 2022-03-31.pdf — 278 rows
  [66/270] 2022-04-07.pdf — 386 rows
  [67/270] 2022-04-15.pdf — 386 rows
  [68/270] 2022-04-19.pdf — 386 rows
  [69/270] 2022-04-28.pdf — 388 rows
  [70/270] 2022-05-05.pdf — 278 rows
  [71/270] 2022-05-12.pdf — 277 rows
  [72/270] 2022-05-20.pdf — 382 rows
  [73/270] 2022-05-26.pdf — 382 rows
  [74/270] 2022-06-02.pdf — 281 rows
  [75/270] 2022-06-09.pdf — 389 rows
  [76/270] 2022-06-14.pdf — 282 rows
  [77/270] 2022-06-23.pdf — 391 rows
  [78/270] 2022-06-30.pdf — 391 rows
  [79/270] 2022-07-07.pdf — 282 rows
  [80/270] 2022-07-14.pdf — 391 rows
  [81/270] 2022-07-21.pdf — 282 rows
  [82/270] 2022-07-28.pdf — 390 rows
  [83/270] 2022-08-04.pdf — 278 rows
  [84/270] 2022-08-11.pdf — 278 rows
  [85/270] 2022-08-18.pdf — 278 rows
  [86/270] 2022-08-25.pdf — 277 rows
  [87/270] 2022-09-01.pdf — 280 rows
  [88/270] 2022-09-06.pdf — 280 rows
  [89/270] 2022-09-15.pdf — 388 rows
  [90/270] 2022-09-23.pdf — 388 rows
  [91/270] 2022-09-29.pdf — 282 rows
  [92/270] 2022-10-06.pdf — 282 rows
  [93/270] 2022-10-13.pdf — 283 rows
  [94/270] 2022-10-18.pdf — 283 rows
  [95/270] 2022-10-27.pdf — 283 rows
  [96/270] 2022-11-03.pdf — 386 rows
  [97/270] 2022-11-10.pdf — 386 rows
  [98/270] 2022-11-17.pdf — 281 rows
  [99/270] 2022-11-26.pdf — 278 rows
  [100/270] 2022-12-03.pdf — 386 rows
  [101/270] 2022-12-09.pdf — 279 rows
  [102/270] 2022-12-15.pdf — 279 rows
  [103/270] 2022-12-22.pdf — 279 rows
  [104/270] 2022-12-29.pdf — 386 rows
  [105/270] 2023-01-05.pdf — 385 rows
  [106/270] 2023-01-12.pdf — 278 rows
  [107/270] 2023-01-20.pdf — 278 rows
  [108/270] 2023-01-26.pdf — 429 rows
  [109/270] 2023-02-03.pdf — 386 rows
  [110/270] 2023-02-10.pdf — 386 rows
  [111/270] 2023-02-17.pdf — 385 rows
  [112/270] 2023-02-23.pdf — 385 rows
  [113/270] 2023-03-02.pdf — 379 rows
  [114/270] 2023-03-10.pdf — 378 rows
  [115/270] 2023-03-17.pdf — 378 rows
  [116/270] 2023-03-24.pdf — 377 rows
  [117/270] 2023-03-31.pdf — 270 rows
  [118/270] 2023-04-09.pdf — 377 rows
  [119/270] 2023-04-13.pdf — 377 rows
  [120/270] 2023-04-20.pdf — 377 rows
  [121/270] 2023-04-27.pdf — 377 rows
  [122/270] 2023-05-06.pdf — 377 rows
  [123/270] 2023-05-12.pdf — 377 rows
  [124/270] 2023-05-19.pdf — 422 rows
  [125/270] 2023-05-25.pdf — 376 rows
  [126/270] 2023-06-01.pdf — 378 rows
  [127/270] 2023-06-08.pdf — 377 rows
  [128/270] 2023-06-15.pdf — 422 rows
  [129/270] 2023-06-24.pdf — 377 rows
  [130/270] 2023-06-29.pdf — 377 rows
  [131/270] 2023-07-07.pdf — 272 rows
  [132/270] 2023-07-14.pdf — 272 rows
  [133/270] 2023-07-21.pdf — 393 rows
  [134/270] 2023-07-28.pdf — 289 rows
  [135/270] 2023-08-03.pdf — 394 rows
  [136/270] 2023-08-11.pdf — 394 rows
  [137/270] 2023-08-17.pdf — 289 rows
  [138/270] 2023-08-24.pdf — 394 rows
  [139/270] 2023-08-31.pdf — 399 rows
  [140/270] 2023-09-14.pdf — 302 rows
  [141/270] 2023-09-21.pdf — 407 rows
  [142/270] 2023-09-28.pdf — 441 rows
  [143/270] 2023-10-05.pdf — 407 rows
  [144/270] 2023-10-12.pdf — 441 rows
  [145/270] 2023-10-17.pdf — 441 rows
  [146/270] 2023-10-26.pdf — 441 rows
  [147/270] 2023-11-03.pdf — 444 rows
  [148/270] 2023-11-09.pdf — 444 rows
  [149/270] 2023-11-16.pdf — 443 rows
  [150/270] 2023-11-23.pdf — 442 rows
  [151/270] 2023-11-30.pdf — 442 rows
  [152/270] 2023-12-07.pdf — 441 rows
  [153/270] 2023-12-14.pdf — 440 rows
  [154/270] 2023-12-22.pdf — 390 rows
  [155/270] 2023-12-28.pdf — 392 rows
  [156/270] 2024-01-04.pdf — 442 rows
  [157/270] 2024-01-09.pdf — 391 rows
  [158/270] 2024-01-16.pdf — 442 rows
  [159/270] 2024-01-25.pdf — 391 rows
  [160/270] 2024-02-01.pdf — 442 rows
  [161/270] 2024-02-05.pdf — 0 rows
  [162/270] 2024-02-15.pdf — 442 rows
  [163/270] 2024-02-27.pdf — 442 rows
  [164/270] 2024-03-05.pdf — 419 rows
  [165/270] 2024-03-12.pdf — 241 rows
  [166/270] 2024-03-19.pdf — 381 rows
  [167/270] 2024-03-26.pdf — 380 rows
  [168/270] 2024-04-02.pdf — 376 rows
  [169/270] 2024-04-09.pdf — 383 rows
  [170/270] 2024-04-16.pdf — 381 rows
  [171/270] 2024-04-23.pdf — 389 rows
  [172/270] 2024-04-30.pdf — 381 rows
  [173/270] 2024-05-07.pdf — 389 rows
  [174/270] 2024-05-14.pdf — 390 rows
  [175/270] 2024-05-21.pdf — 379 rows
  [176/270] 2024-05-28.pdf — 390 rows
  [177/270] 2024-06-04.pdf — 387 rows
  [178/270] 2024-06-11.pdf — 381 rows
  [179/270] 2024-06-18.pdf — 388 rows
  [180/270] 2024-06-25.pdf — 380 rows
  [181/270] 2024-07-02.pdf — 399 rows
  [182/270] 2024-07-09.pdf — 405 rows
  [183/270] 2024-07-16.pdf — 389 rows
  [184/270] 2024-07-23.pdf — 383 rows
  [185/270] 2024-07-30.pdf — 393 rows
  [186/270] 2024-08-06.pdf — 383 rows
  [187/270] 2024-08-13.pdf — 389 rows
  [188/270] 2024-08-20.pdf — 389 rows
  [189/270] 2024-08-27.pdf — 393 rows
  [190/270] 2024-09-03.pdf — 393 rows
  [191/270] 2024-09-10.pdf — 387 rows
  [192/270] 2024-09-17.pdf — 392 rows
  [193/270] 2024-09-24.pdf — 395 rows
  [194/270] 2024-10-01.pdf — 389 rows
  [195/270] 2024-10-08.pdf — 389 rows
  [196/270] 2024-10-15.pdf — 393 rows
  [197/270] 2024-10-22.pdf — 393 rows
  [198/270] 2024-10-29.pdf — 398 rows
  [199/270] 2024-11-05.pdf — 396 rows
  [200/270] 2024-11-12.pdf — 396 rows
  [201/270] 2024-11-19.pdf — 396 rows
  [202/270] 2024-11-26.pdf — 398 rows
  [203/270] 2024-12-03.pdf — 396 rows
  [204/270] 2024-12-10.pdf — 396 rows
  [205/270] 2024-12-17.pdf — 396 rows
  [206/270] 2024-12-24.pdf — 398 rows
  [207/270] 2025-01-07.pdf — 400 rows
  [208/270] 2025-01-14.pdf — 400 rows
  [209/270] 2025-01-21.pdf — 398 rows
  [210/270] 2025-01-28.pdf — 404 rows
  [211/270] 2025-02-04.pdf — 404 rows
  [212/270] 2025-02-11.pdf — 403 rows
  [213/270] 2025-02-18.pdf — 402 rows
  [214/270] 2025-02-25.pdf — 402 rows
  [215/270] 2025-03-04.pdf — 402 rows
  [216/270] 2025-03-11.pdf — 400 rows
  [217/270] 2025-03-18.pdf — 402 rows
  [218/270] 2025-03-25.pdf — 401 rows
  [219/270] 2025-04-01.pdf — 401 rows
  [220/270] 2025-04-08.pdf — 402 rows
  [221/270] 2025-04-15.pdf — 397 rows
  [222/270] 2025-04-22.pdf — 397 rows
  [223/270] 2025-04-29.pdf — 404 rows
  [224/270] 2025-05-06.pdf — 404 rows
  [225/270] 2025-05-13.pdf — 404 rows
  [226/270] 2025-05-20.pdf — 402 rows
  [227/270] 2025-06-10.pdf — 402 rows
  [228/270] 2025-06-17.pdf — 404 rows
  [229/270] 2025-06-24.pdf — 404 rows
  [230/270] 2025-07-01.pdf — 402 rows
  [231/270] 2025-07-08.pdf — 404 rows
  [232/270] 2025-07-15.pdf — 404 rows
  [233/270] 2025-07-22.pdf — 403 rows
  [234/270] 2025-07-29.pdf — 405 rows
  [235/270] 2025-08-05.pdf — 403 rows
  [236/270] 2025-08-12.pdf — 402 rows
  [237/270] 2025-08-19.pdf — 402 rows
  [238/270] 2025-08-26.pdf — 402 rows
  [239/270] 2025-09-02.pdf — 405 rows
  [240/270] 2025-09-09.pdf — 402 rows
  [241/270] 2025-09-16.pdf — 402 rows
  [242/270] 2025-09-23.pdf — 406 rows
  [243/270] 2025-09-30.pdf — 409 rows
  [244/270] 2025-10-07.pdf — 404 rows
  [245/270] 2025-10-14.pdf — 402 rows
  [246/270] 2025-10-21.pdf — 404 rows
  [247/270] 2025-10-28.pdf — 402 rows
  [248/270] 2025-11-04.pdf — 402 rows
  [249/270] 2025-11-11.pdf — 402 rows
  [250/270] 2025-11-18.pdf — 402 rows
  [251/270] 2025-11-25.pdf — 401 rows
  [252/270] 2025-12-02.pdf — 402 rows
  [253/270] 2025-12-09.pdf — 402 rows
  [254/270] 2025-12-16.pdf — 402 rows
  [255/270] 2025-12-23.pdf — 400 rows
  [256/270] 2025-12-30.pdf — 400 rows
  [257/270] 2026-01-06.pdf — 299 rows
  [258/270] 2026-01-13.pdf — 299 rows
  [259/270] 2026-01-20.pdf — 403 rows
  [260/270] 2026-01-27.pdf — 390 rows
  [261/270] 2026-02-03.pdf — 403 rows
  [262/270] 2026-02-10.pdf — 402 rows
  [263/270] 2026-02-17.pdf — 401 rows
  [264/270] 2026-02-24.pdf — 396 rows
  [265/270] 2026-03-03.pdf — 393 rows
  [266/270] 2026-03-10.pdf — 490 rows
  [267/270] 2026-03-17.pdf — 498 rows
  [268/270] 2026-03-24.pdf — 552 rows
  [269/270] 2026-03-31.pdf — 545 rows
  [270/270] 2026-04-07.pdf — 334 rows
CSV  saved → data/semi_cleaned_data/DOE_NCR_OilPrices_Compiled.csv  (98,951 rows)

### Section 2: Cleaning

In [4]:
from functions import dti_pipeline as dp

In [9]:
# load data
directory_dti = r'data/uncleaned_data/prevailing_prices.xlsx'
df_dti_clean = dp.load_pp(directory_dti)
df_dti_fu_clean = dp.add_standardize(df_dti_clean)

# try
dfq = df_dti_fu_clean['2026']
d_2 = df_dti_fu_clean['2025']

display(dfq)
display(d_2)

                     commodity      brand specification    jan    feb
0    Bottled Water - Distilled   Absolute         250ml    9.5    9.5
1    Bottled Water - Distilled   Absolute         350ml     12     12
2    Bottled Water - Distilled   Absolute         500ml  16.25  16.25
3    Bottled Water - Distilled   Absolute            1L     25     25
4    Bottled Water - Distilled   Absolute          1.5L   37.5     35
..                         ...        ...           ...    ...    ...
689                Toilet Soap  Safeguard           65g     20     20
690                Toilet Soap  Safeguard           65g     20     20
691                Toilet Soap  Safeguard           65g   21.5   21.5
692                Toilet Soap  Safeguard           65g   18.5   18.5
693                Toilet Soap  Safeguard           65g   21.5     20

[693 rows x 5 columns]

,commodity,brand,specification,jan,feb,mar,apr,may,jun,jul,aug,sept,oct,nov,dec
1,Bottled Water - Distilled,Absolute,250ml,9.25,9.25,9.25,9.5,9.5,9.5,9.5,9.5,9.5,9.5,9.5,9.5
2,Bottled Water - Distilled,Absolute,350ml,12,12,12,12,12,12,12,12,12,12,12,12
3,Bottled Water - Distilled,Absolute,500ml,16.25,16.25,16.25,16.25,16.25,16.25,16.25,16.25,16.25,16.25,16.25,16.25
4,Bottled Water - Distilled,Absolute,1L,25,25,25,25,25,25,25,25,25,25,25,25
5,Bottled Water - Distilled,Absolute,1.5L,42.5,37,37,35,35,35,35,36,36,35,35,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,Soft Flour,Penguin,25kg/bag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,760,NaN
670,Soft Flour,Red Dragon,25kg/bag,NaN,NaN,NaN,NaN,NaN,850,NaN,NaN,NaN,890,NaN,NaN
671,Soft Flour,Snow White,25kg/bag,NaN,NaN,NaN,NaN,NaN,950,NaN,NaN,NaN,NaN,NaN,NaN
672,Soft Flour,Supremo,25kg/bag,NaN,NaN,NaN,NaN,950,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673,Soft Flour,White Pigeon,25kg/bag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,730,NaN,NaN

In [18]:
# Load the raw Excel sheets
directory_dti = r'data/uncleaned_data/prevailing_prices.xlsx'

# load
df_dti_clean = dp.load_pp(directory_dti)

# standardize
df_dti_clean = dp.add_standardize(df_dti_clean)

# save each cleaned df as a CSV
output_folder = 'data/semi_cleaned_data' # saved to semi_cleaned folder
os.makedirs(output_folder, exist_ok=True)

for year, df in df_dti_clean.items():
    filename = os.path.join(output_folder, f"{year}_cleaned.csv")
    df.to_csv(filename, index=False)
    print(f"Saved {filename}")

Saved data/semi_cleaned_data/2020_cleaned.csv
Saved data/semi_cleaned_data/2021_cleaned.csv
Saved data/semi_cleaned_data/2022_cleaned.csv
Saved data/semi_cleaned_data/2023_cleaned.csv
Saved data/semi_cleaned_data/2024_cleaned.csv
Saved data/semi_cleaned_data/2025_cleaned.csv
Saved data/semi_cleaned_data/2026_cleaned.csv

In [20]:
# path to the folder containing your 2020_cleaned.csv, 2021_cleaned.csv, etc.
CSV_DIR   = "data/semi_cleaned_data"

# path specifically to the Excel file (not just the folder)
XLSX_PATH = "data/uncleaned_data/prevailing_prices.xlsx"

# run the pipeline
panel, reports = dp.run_dti_pipeline(CSV_DIR, XLSX_PATH)

# diagnostics
print(f"Panel Shape: {panel.shape}")
display(panel.head())

# validation report
print("\nCoverage Check")
print(reports["validation"]["coverage"].head())

print(f"\nSpikes repaired: {reports['validation']['n_spikes_repaired'].iloc[0,0]}")
print(f"Bimodal series detected: {len(reports['validation']['bimodal_series'])}")

# Save the final cleaned weekly panel
panel.to_parquet("data/semi_cleaned_data/dti_weekly_panel.parquet", index=False)
panel.to_csv("data/semi_cleaned_data/dti_weekly_panel.csv")

[drop_empty_specs] dropping 72 rows with empty spec:
     commodity    brand  n_rows
bread pandesal gardenia      36
bread pandesal    marby      36
[harmonize_candle_specs] dropping 1066 rows from non-winning candle spec families:
     brand specification  n_rows
    5 star         20pcs      30
    5 star         25pcs      30
    5 star          2pcs      30
    5 star          4pcs      30
    5 star          5pcs      30
    export         10pcs      52
    export         12pcs      82
    export         20pcs      78
    export          2pcs      14
    export          4pcs     144
    export          6pcs      52
    export          8pcs      26
   liwanag        size03      36
   liwanag        size05      36
   liwanag        size16      36
   liwanag        size18      36
   liwanag        size24      36
manila wax        size01      36
manila wax        size02      72
manila wax        size03      72
manila wax        size04      36
manila wax        size14      36
manila wax        size16      36
Panel Shape: (35115, 11)

,date,series_id,category,commodity,brand,specification,price,log_price,dlog_1w,dlog_4w,dlog_8w
0,2023-10-02,battery|energizer|4pcs,prime,battery,energizer,4pcs,196.5,5.280662,NaN,NaN,NaN
1,2023-10-09,battery|energizer|4pcs,prime,battery,energizer,4pcs,196.5,5.280662,0.0,NaN,NaN
2,2023-10-16,battery|energizer|4pcs,prime,battery,energizer,4pcs,196.5,5.280662,0.0,NaN,NaN
3,2023-10-23,battery|energizer|4pcs,prime,battery,energizer,4pcs,196.5,5.280662,0.0,NaN,NaN
4,2023-10-30,battery|energizer|4pcs,prime,battery,energizer,4pcs,196.5,5.280662,0.0,0.0,NaN

Coverage Check
                                   n_weeks      start        end  mean_price
commodity brand     specification
battery   energizer 4pcs               126 2023-10-02 2026-02-23  199.827381
                    aa_4pcs            156 2020-01-06 2022-12-26  177.963141
          eveready  2pcs               130 2023-09-04 2026-02-23   72.994263
                    aa_2pcs            156 2020-01-06 2022-12-26   33.188304
                    d_2pcs             156 2020-01-06 2022-12-26   55.738679

Spikes repaired: 147
Bimodal series detected: 26

In [22]:
python3 functions/run_pipeline.py

SyntaxError: invalid syntax (963116184.py, line 1)